const webpack = require('webpack');

module.exports = {
  entry: './markdown-converter.js',
  // the generated converter will be usable as MarkdownConverter.render("**Markdown** _string_")
  // when included in a <script> tag
  output: {
    library: "MarkdownConverter",
    filename: 'build/markdown-converter.js'
  },
  plugins: [
    // add a notice to the generated file informing that it was generated from here
    new webpack.BannerPlugin({
      banner: 'File generated by running `npm run build` in PROJECT_ROOT/markdown folder'
    })
  ]
}
