package me.vickychijwani.spectre.network;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;

import java.lang.reflect.Type;

import me.vickychijwani.spectre.model.Post;
import me.vickychijwani.spectre.model.Tag;

// TODO can be deleted now?
public class PostSerializer implements JsonSerializer<Post> {

    @Override
    public JsonElement serialize(Post post, Type typeOfSrc, JsonSerializationContext context) {
        JsonObject json = new JsonObject();
        json.addProperty("title", post.getTitle());
        json.addProperty("status", post.getStatus());
        json.addProperty("markdown", post.getMarkdown());

        JsonArray tags = new JsonArray();
        for (Tag tag : post.getTags()) {
            tags.add(context.serialize(tag, Tag.class));
        }
        json.add("tags", tags);

        // html, slug, and timestamps omitted, generated by server

        return json;
    }

}
