package me.vickychijwani.spectre.model;

import android.support.annotation.NonNull;

import org.parceler.Parcel;

import java.util.Date;

import io.realm.Realm;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.realm.annotations.RealmClass;

@RealmClass
@Parcel(value = Parcel.Serialization.BEAN, analyze = { Post.class })
public class Post extends RealmObject {

    public static final String LOCAL_NEW = "local_new";
    public static final String DRAFT = "draft";
    public static final String PUBLISHED = "published";

    @PrimaryKey
    private String uuid = null;
    private int id;
    private String title = "(Untitled)";
    private String slug = null;
    private String status = LOCAL_NEW;   // can be local_new, draft, or published

    private String markdown = "";
    private String html = "";

    private Date createdAt = null;
    private Date updatedAt = FAR_FUTURE;   // so that locally-created posts will be sorted to the top
    private Date publishedAt = null;

    private transient boolean isUploaded = false;   // temporary flag, never serialized

    // 2114380800 seconds in epoch time == 01/01/2037 @ 12:00am (UTC)
    private static final Date FAR_FUTURE = new Date(2114380800L * 1000);

    // generates a temporary primary key until the actual id is generated by the server
    public static String getTempUniqueId(Realm realm) {
        int tempId = Integer.MAX_VALUE;
        while (realm.where(Post.class).equalTo("uuid", String.valueOf(tempId)).findAll().size() > 0) {
            --tempId;
        }
        return String.valueOf(tempId);
    }

    // NOTE: DO NOT ADD / MODIFY METHODS, SEE https://realm.io/docs/java/#faq
    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getMarkdown() {
        return markdown;
    }

    public void setMarkdown(String markdown) {
        this.markdown = markdown;
    }

    public String getHtml() {
        return html;
    }

    public void setHtml(String html) {
        this.html = html;
    }

    @NonNull
    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @NonNull
    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @NonNull
    public Date getPublishedAt() {
        return publishedAt;
    }

    public void setPublishedAt(Date publishedAt) {
        this.publishedAt = publishedAt;
    }

    public boolean isUploaded() {
        return isUploaded;
    }

    public void setUploaded(boolean isUploaded) {
        this.isUploaded = isUploaded;
    }

}
